import { BuildingType, TerrainType } from './types';

export const BUILDINGS: Record<string, BuildingType> = {
  // --- TIER 0: PRIMITIVE (No complex inputs, easy start) ---
  forager: {
    id: 'forager',
    name: 'Forager Hut',
    description: 'Gathers food from the wild. Inefficient.',
    cost: { wood: 5 },
    inputs: { population: 0.1 },
    outputs: { food: 0.5 },
    labor: 0,
    requiresTerrain: ['plains', 'forest'],
    unlockEra: 1,
    upgradesTo: 'farm',
    upgradeCost: { wood: 20, stone: 10 },
  },
  wood_camp: {
    id: 'wood_camp',
    name: 'Wood Camp',
    description: 'Basic wood gathering operation.',
    cost: {}, // Free to start
    inputs: { population: 0.1 },
    outputs: { wood: 0.5 },
    labor: 0,
    requiresTerrain: ['forest'],
    unlockEra: 1,
    upgradesTo: 'lumber_mill',
    upgradeCost: { wood: 50, tools: 5 },
  },
  stone_camp: {
    id: 'stone_camp',
    name: 'Stone Camp',
    description: 'Gathers loose stone.',
    cost: { wood: 10 },
    inputs: { population: 0.1 },
    outputs: { stone: 0.5 },
    labor: 0,
    requiresTerrain: ['mountain', 'plains'],
    unlockEra: 1,
    upgradesTo: 'quarry',
    upgradeCost: { wood: 50, tools: 10 },
  },
  workshop: {
    id: 'workshop',
    name: 'Workshop',
    description: 'Cobbles together basic tools from stone and wood.',
    cost: { wood: 20 },
    inputs: { wood: 0.5, stone: 0.25, population: 0.1 },
    outputs: { tools: 0.2 },
    labor: 0,
    unlockEra: 1,
    upgradesTo: 'tool_factory',
    upgradeCost: { stone: 100, iron_ingot: 20 },
  },
  surface_mine: {
    id: 'surface_mine',
    name: 'Surface Iron',
    description: 'Collects surface iron deposits.',
    cost: { wood: 30, stone: 10 },
    inputs: { population: 0.2, tools: 0.1 },
    outputs: { iron_ore: 0.5 },
    labor: 0,
    requiresTerrain: ['mountain'],
    unlockEra: 1,
    upgradesTo: 'iron_mine',
    upgradeCost: { wood: 100, stone: 100, tools: 20 },
  },
  surface_coal: {
    id: 'surface_coal',
    name: 'Surface Coal',
    description: 'Collects surface coal deposits.',
    cost: { wood: 30, stone: 10 },
    inputs: { population: 0.2, tools: 0.1 },
    outputs: { coal: 0.5 },
    labor: 0,
    requiresTerrain: ['mountain'],
    unlockEra: 1,
    upgradesTo: 'coal_mine',
    upgradeCost: { wood: 100, stone: 100, tools: 20 },
  },
  bloomery: {
    id: 'bloomery',
    name: 'Bloomery',
    description: 'A primitive furnace for smelting iron using wood fuel.',
    cost: { stone: 40, wood: 20 },
    inputs: { iron_ore: 1, wood: 2, population: 0.2 },
    outputs: { iron_ingot: 0.5 },
    labor: 0,
    unlockEra: 1,
    upgradesTo: 'smelter',
    upgradeCost: { stone: 100, wood: 50, iron_ingot: 10 },
  },

  // --- TIER 1: INDUSTRIAL (Requires Infrastructure & Tools) ---
  farm: {
    id: 'farm',
    name: 'Farm',
    description: 'Produces food from fertile plains.',
    cost: { wood: 50, stone: 20 },
    inputs: { population: 0.1, tools: 0.1 },
    outputs: { food: 2 },
    labor: 0,
    requiresTerrain: ['plains'],
    unlockEra: 1,
  },
  lumber_mill: {
    id: 'lumber_mill',
    name: 'Lumber Mill',
    description: 'Industrial wood processing.',
    cost: { wood: 100, tools: 10 },
    inputs: { population: 0.2, tools: 0.2 },
    outputs: { wood: 3 },
    labor: 0,
    requiresTerrain: ['forest'],
    unlockEra: 2,
  },
  quarry: {
    id: 'quarry',
    name: 'Ind. Quarry',
    description: 'Deep stone excavation.',
    cost: { wood: 100, tools: 10 },
    inputs: { population: 0.5, tools: 0.2 },
    outputs: { stone: 3 },
    labor: 0,
    requiresTerrain: ['mountain'],
    unlockEra: 2,
  },
  iron_mine: {
    id: 'iron_mine',
    name: 'Deep Iron Mine',
    description: 'Deep shaft mining. Very slow without tools.',
    cost: { stone: 200, tools: 20 },
    inputs: { population: 1.0, tools: 0.5 },
    outputs: { iron_ore: 4 },
    labor: 0,
    requiresTerrain: ['mountain'],
    unlockEra: 2,
  },
  coal_mine: {
    id: 'coal_mine',
    name: 'Deep Coal Mine',
    description: 'Deep shaft mining. Very slow without tools.',
    cost: { stone: 200, tools: 20 },
    inputs: { population: 1.0, tools: 0.5 },
    outputs: { coal: 4 },
    labor: 0,
    requiresTerrain: ['mountain'],
    unlockEra: 2,
  },
  smelter: {
    id: 'smelter',
    name: 'Smelter',
    description: 'Refines ore. Requires Fuel.',
    cost: { stone: 100, wood: 50 },
    inputs: { iron_ore: 2, coal: 1, population: 0.5 },
    outputs: { iron_ingot: 1 },
    labor: 0,
    unlockEra: 2,
  },
  tool_factory: {
    id: 'tool_factory',
    name: 'Tool Factory',
    description: 'Mass produces high-quality tools.',
    cost: { stone: 200, iron_ingot: 50 },
    inputs: { iron_ingot: 1, wood: 1, coal: 0.5, population: 0.5 },
    outputs: { tools: 3 },
    labor: 0,
    unlockEra: 2,
  },
  concrete_factory: {
    id: 'concrete_factory',
    name: 'Concrete Plant',
    description: 'Mixes concrete.',
    cost: { stone: 200, iron_ingot: 20 },
    inputs: { stone: 5, coal: 1, population: 0.5 },
    outputs: { concrete: 2 },
    labor: 0,
    unlockEra: 3,
  },
  steel_mill: {
    id: 'steel_mill',
    name: 'Steel Mill',
    description: 'Advanced metallurgy.',
    cost: { iron_ingot: 100, concrete: 50 },
    inputs: { iron_ingot: 3, coal: 3, tools: 0.5, population: 1.0 },
    outputs: { steel: 2 },
    labor: 0,
    unlockEra: 3,
  },
  // --- RESIDENTIAL (Population Production) ---
  settlement: {
    id: 'settlement',
    name: 'Settlement',
    description: 'A small community. Consumes food to grow population.',
    cost: { wood: 20 },
    inputs: { food: 2 },
    outputs: { population: 1 },
    labor: 0,
    requiresTerrain: ['plains', 'forest'],
    unlockEra: 1,
    upgradesTo: 'town',
    upgradeCost: { wood: 100, stone: 50 },
  },
  town: {
    id: 'town',
    name: 'Town',
    description: 'A growing town. Needs robust food supply.',
    cost: { wood: 100, stone: 50 },
    inputs: { food: 5, tools: 0.1 },
    outputs: { population: 3 },
    labor: 0,
    requiresTerrain: ['plains'],
    unlockEra: 2,
    upgradesTo: 'city',
    upgradeCost: { stone: 200, iron_ingot: 50, concrete: 50 },
  },
  city: {
    id: 'city',
    name: 'City',
    description: 'A major metropolis. Requires massive food and goods.',
    cost: { stone: 200, iron_ingot: 50, concrete: 50 },
    inputs: { food: 15, tools: 0.5, coal: 0.5 },
    outputs: { population: 10 },
    labor: 0,
    requiresTerrain: ['plains'],
    unlockEra: 3,
  },
};

export const TERRAIN_COLORS: Record<TerrainType, string> = {
  plains: '#90be6d', // Green
  forest: '#43aa8b', // Darker Green
  mountain: '#777',   // Gray
  water: '#277da1',   // Blue
};
